version: '3'

services:
  db:
    image: mysql:5.6.27
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql/:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    environment:
      SOCIAL_AUTH_FACEBOOK_KEY: ${SOCIAL_AUTH_FACEBOOK_KEY}
      SOCIAL_AUTH_FACEBOOK_SECRET: ${SOCIAL_AUTH_FACEBOOK_SECRET}
      DJANGO_SETTINGS_MODULE: conf.settings.local
    volumes:
      - ./rugbystat/:/workspace
    depends_on:
      - db
    ports:
      - "8000:8000"
      - "1488:1488"
