[project]
name = "rugbystat"
version = "1.0.0"
description = "Soviet rugby statistics engine"
authors = [{ name = "krnr", email = "ultrasnet@mail.ru" }]
requires-python = "~=3.13"
dependencies = [
    "django~=5.0",
    "django-extensions",
    "django-model-utils",
    "django-widget-tweaks",
    "django-admin-sortable2",
    "django-allauth",
    "django-autocomplete-light",
    "django-filter",
    "django-markdownx",
    # "django-versatileimagefield",
    "djangorestframework",
    "dj-database-url",
    "mysqlclient",
    "dropbox",
    "django-dropbox",
    "django-storages",
    "whitenoise",
    "diskcache",
    "babel",
    "pillow>11",
    "fuzzywuzzy[speedup]",
    "lxml",
    "dateparser",
    "pyjwt>=2.10.1",
    "cryptography>=46.0.3",
    "six>=1.17.0",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=6.0.0",
]

[tool.uv]

[tool.uv.sources]
django-dropbox = { git = "https://github.com/krnr/django-dropbox/", tag="0.1.3"}
