# Generated by Django 2.2.24 on 2024-01-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clippings', '0016_auto_20210106_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dropbox_path',
            field=models.URLField(blank=True, max_length=255, verbose_name='Прямая ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='dropbox_thumb',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Прямая ссылка на превью'),
        ),
    ]
