# Generated by Django 2.2.24 on 2024-01-03 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0035_auto_20210106_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupseason',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='О'),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='О'),
        ),
    ]
